add check if test exist before upload and delete after upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,6 +5,11 @@ inputs:
   unityPath:
     description: 'The full path to the Unity executable.'
     required: true
+    
+  projectPath:
+    description: 'The path to the project root.'
+    default: '.'
+    required: false
 
 runs:
   using: 'composite'
@@ -15,21 +20,36 @@ runs:
     - name: Unity Play Mode Test
       shell: cmd
       run: |
-        "${{ inputs.unityPath }}" -batchmode -projectPath . -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile -
+        "${{ inputs.unityPath }}" -batchmode -projectPath ${{ inputs.projectPath }} -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile -
 
     - name: Unity Editor Mode Test
       shell: cmd
       run: |
-        "${{ inputs.unityPath }}" -batchmode -projectPath . -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile -
+        "${{ inputs.unityPath }}" -batchmode -projectPath ${{ inputs.projectPath }} -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile -
+
+    - name: Check if XML Test Results Exist
+      shell: cmd
+      run: |
+        if [ ! -f "TestResult-PlayMode.xml" ] || [ ! -f "TestResult-EditMode.xml" ]; then
+          echo "One or both XML test result files are missing."
+          exit 1
+        fi
 
     - name: Upload Test Results
+      if: success()  # Only run this step if the previous steps were successful.
       uses: actions/upload-artifact@v3
       with:
         name: Test Results
         path: |
           TestResult-PlayMode.xml
           TestResult-EditMode.xml
-      
+
+    - name: Delete XML Test Results
+      if: always()  # Always run this step, regardless of previous step status.
+      shell: cmd
+      run: |
+        rm -f "TestResult-PlayMode.xml" "TestResult-EditMode.xml"
+
 branding:
   icon: 'arrow-up-circle'
-  color: 'gray-dark'          
+  color: 'gray-dark'
